"""Steam Guard helpers: TOTP codes, confirmation keys and device ids."""

from __future__ import annotations

import hmac
import json
import struct
from base64 import b64decode, b64encode
from hashlib import sha1
from pathlib import Path
from time import time

# Steam's TOTP implementation: 30-second steps encoded with a custom alphabet.
_TOTP_STEP_SECONDS = 30
_TOTP_CODE_LENGTH = 5
_TOTP_ALPHABET = "23456789BCDFGHJKMNPQRTVWXY"


def load_steam_guard(steam_guard: str) -> dict[str, str]:
    """Load Steam Guard credentials from a json file or a json string.

    Args:
        steam_guard: A path to a json file or a json string. When the value
            points to an existing file its contents are parsed, otherwise the
            value itself is parsed as json.

    Returns:
        The parsed Steam Guard data with every value coerced to ``str``.
    """
    if Path(steam_guard).is_file():
        with Path(steam_guard).open(encoding="utf-8") as f:
            return json.loads(f.read(), parse_int=str)
    return json.loads(steam_guard, parse_int=str)


def generate_one_time_code(shared_secret: str, timestamp: int | None = None) -> str:
    """Generate the current Steam Guard TOTP code from a shared secret.

    Args:
        shared_secret: The base64-encoded ``shared_secret`` of the account.
        timestamp: Unix time to generate the code for; defaults to ``now``.

    Returns:
        The five-character one-time code.
    """
    if timestamp is None:
        timestamp = int(time())
    time_buffer = struct.pack(
        ">Q", timestamp // _TOTP_STEP_SECONDS
    )  # big-endian uint64
    time_hmac = hmac.new(b64decode(shared_secret), time_buffer, digestmod=sha1).digest()
    begin = ord(time_hmac[19:20]) & 0xF
    full_code = (
        struct.unpack(">I", time_hmac[begin : begin + 4])[0] & 0x7FFFFFFF
    )  # uint32
    code = ""
    for _ in range(_TOTP_CODE_LENGTH):
        full_code, i = divmod(full_code, len(_TOTP_ALPHABET))
        code += _TOTP_ALPHABET[i]
    return code


def generate_confirmation_key(
    identity_secret: str,
    tag: str,
    timestamp: int | None = None,
) -> bytes:
    """Generate the HMAC key Steam expects for a mobile confirmation request.

    Args:
        identity_secret: The base64-encoded ``identity_secret`` of the account.
        tag: The confirmation tag (for example ``conf`` or ``allow``).
        timestamp: Unix time for the request; defaults to ``now``.

    Returns:
        The base64-encoded confirmation key.
    """
    if timestamp is None:
        timestamp = int(time())
    buffer = struct.pack(">Q", timestamp) + tag.encode("ascii")
    return b64encode(
        hmac.new(b64decode(identity_secret), buffer, digestmod=sha1).digest()
    )


def generate_device_id(steam_id: str) -> str:
    """Derive the Android device id Steam associates with a confirmation.

    The value is deterministic for a given ``steam_id``; it differs from the id
    generated by the official mobile app but is accepted by the confirmation
    endpoints.
    """
    hexed_steam_id = sha1(steam_id.encode("ascii")).hexdigest()
    return "android:" + "-".join(
        (
            hexed_steam_id[:8],
            hexed_steam_id[8:12],
            hexed_steam_id[12:16],
            hexed_steam_id[16:20],
            hexed_steam_id[20:32],
        )
    )
